--!strict
-- Starter Brainrot definitions. ModelName values must match Blender exports and Roblox model names.

local BrainrotConfig = {}

BrainrotConfig.RarityOrder = {
	Common = 1,
	Uncommon = 2,
	Rare = 3,
	Epic = 4,
	Legendary = 5,
	Mythic = 6,
	Secret = 7,
}

BrainrotConfig.RarityColors = {
	Common = Color3.fromRGB(236, 242, 248),
	Uncommon = Color3.fromRGB(111, 236, 135),
	Rare = Color3.fromRGB(77, 174, 255),
	Epic = Color3.fromRGB(194, 91, 255),
	Legendary = Color3.fromRGB(255, 199, 61),
	Mythic = Color3.fromRGB(255, 83, 166),
	Secret = Color3.fromRGB(67, 255, 192),
}

BrainrotConfig.List = {
	{
		Id = "WobbleNugget",
		DisplayName = "Wobble Nugget",
		Rarity = "Common",
		CashPerSecond = 6,
		CaptureReward = 45,
		HP = 30,
		Speed = 10,
		SpawnWeight = 28,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_WobbleNugget",
		IconAssetId = nil,
		ShowcaseScale = 1,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "GoofyCone",
		DisplayName = "Goofy Cone",
		Rarity = "Common",
		CashPerSecond = 7,
		CaptureReward = 55,
		HP = 34,
		Speed = 10,
		SpawnWeight = 26,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_GoofyCone",
		IconAssetId = nil,
		ShowcaseScale = 1.05,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "TinyBloop",
		DisplayName = "Tiny Bloop",
		Rarity = "Common",
		CashPerSecond = 8,
		CaptureReward = 65,
		HP = 28,
		Speed = 12,
		SpawnWeight = 24,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_TinyBloop",
		IconAssetId = nil,
		ShowcaseScale = 0.85,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "SneakyPickle",
		DisplayName = "Sneaky Pickle",
		Rarity = "Uncommon",
		CashPerSecond = 12,
		CaptureReward = 110,
		HP = 45,
		Speed = 13,
		SpawnWeight = 18,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_SneakyPickle",
		IconAssetId = nil,
		ShowcaseScale = 1.08,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "DizzyDonut",
		DisplayName = "Dizzy Donut",
		Rarity = "Uncommon",
		CashPerSecond = 14,
		CaptureReward = 130,
		HP = 52,
		Speed = 11,
		SpawnWeight = 16,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_DizzyDonut",
		IconAssetId = nil,
		ShowcaseScale = 1.12,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "BananaGoblin",
		DisplayName = "Banana Goblin",
		Rarity = "Rare",
		CashPerSecond = 22,
		CaptureReward = 240,
		HP = 68,
		Speed = 14,
		SpawnWeight = 10,
		ZoneUnlockRequirement = "Starter",
		ModelName = "BR_BananaGoblin",
		IconAssetId = nil,
		ShowcaseScale = 1.1,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "ShyToaster",
		DisplayName = "Shy Toaster",
		Rarity = "Rare",
		CashPerSecond = 26,
		CaptureReward = 290,
		HP = 76,
		Speed = 10,
		SpawnWeight = 9,
		ZoneUnlockRequirement = "Forest",
		ModelName = "BR_ShyToaster",
		IconAssetId = nil,
		ShowcaseScale = 1.08,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "TurboMeatball",
		DisplayName = "Turbo Meatball",
		Rarity = "Epic",
		CashPerSecond = 45,
		CaptureReward = 560,
		HP = 105,
		Speed = 16,
		SpawnWeight = 5,
		ZoneUnlockRequirement = "Forest",
		ModelName = "BR_TurboMeatball",
		IconAssetId = nil,
		ShowcaseScale = 1.18,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "GlitchyCapybara",
		DisplayName = "Glitchy Capybara",
		Rarity = "Epic",
		CashPerSecond = 54,
		CaptureReward = 690,
		HP = 120,
		Speed = 15,
		SpawnWeight = 4,
		ZoneUnlockRequirement = "Crystal",
		ModelName = "BR_GlitchyCapybara",
		IconAssetId = nil,
		ShowcaseScale = 1.2,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "BubbleLizard",
		DisplayName = "Bubble Lizard",
		Rarity = "Legendary",
		CashPerSecond = 95,
		CaptureReward = 1400,
		HP = 175,
		Speed = 17,
		SpawnWeight = 2,
		ZoneUnlockRequirement = "Crystal",
		ModelName = "BR_BubbleLizard",
		IconAssetId = nil,
		ShowcaseScale = 1.24,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "GoldenSpaghettiKing",
		DisplayName = "Golden Spaghetti King",
		Rarity = "Mythic",
		CashPerSecond = 180,
		CaptureReward = 3500,
		HP = 260,
		Speed = 15,
		SpawnWeight = 0.75,
		ZoneUnlockRequirement = "Lava",
		ModelName = "BR_GoldenSpaghettiKing",
		IconAssetId = nil,
		ShowcaseScale = 1.35,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
	{
		Id = "CosmicBrainFrog",
		DisplayName = "Cosmic Brain Frog",
		Rarity = "Secret",
		CashPerSecond = 420,
		CaptureReward = 10000,
		HP = 420,
		Speed = 18,
		SpawnWeight = 0.18,
		ZoneUnlockRequirement = "Galaxy",
		ModelName = "BR_CosmicBrainFrog",
		IconAssetId = nil,
		ShowcaseScale = 1.38,
		ShowcaseRotationOffset = Vector3.new(0, 0, 0),
		IdleAnimationId = nil,
		RunAnimationId = nil,
		StunAnimationId = nil,
		Mutation = {},
	},
}

BrainrotConfig.ById = {}
BrainrotConfig.ByModelName = {}

for _, entry in ipairs(BrainrotConfig.List) do
	BrainrotConfig.ById[entry.Id] = entry
	BrainrotConfig.ByModelName[entry.ModelName] = entry
end

function BrainrotConfig.GetById(id: string)
	return BrainrotConfig.ById[id]
end

function BrainrotConfig.GetByModelName(modelName: string)
	return BrainrotConfig.ByModelName[modelName]
end

return BrainrotConfig
