return {
	ByteBunny = {
		Name = "Byte Bunny",
		Rarity = "Common",
		Zone = "Grass",
		BaseHP = 35,
		BaseSpeed = 10,
		MoneyPerSecond = 3,
		Color = Color3.fromRGB(127, 225, 255),
	},
	ToastGhost = {
		Name = "Toast Ghost",
		Rarity = "Common",
		Zone = "Grass",
		BaseHP = 42,
		BaseSpeed = 9,
		MoneyPerSecond = 4,
		Color = Color3.fromRGB(255, 225, 163),
	},
	PuddlePup = {
		Name = "Puddle Pup",
		Rarity = "Rare",
		Zone = "Grass",
		BaseHP = 60,
		BaseSpeed = 11,
		MoneyPerSecond = 8,
		Color = Color3.fromRGB(76, 164, 255),
	},
	CactusCat = {
		Name = "Cactus Cat",
		Rarity = "Rare",
		Zone = "Desert",
		BaseHP = 90,
		BaseSpeed = 12,
		MoneyPerSecond = 18,
		Color = Color3.fromRGB(93, 196, 102),
	},
	DuneDuck = {
		Name = "Dune Duck",
		Rarity = "Epic",
		Zone = "Desert",
		BaseHP = 130,
		BaseSpeed = 13,
		MoneyPerSecond = 42,
		Color = Color3.fromRGB(255, 188, 75),
	},
	FrostFrog = {
		Name = "Frost Frog",
		Rarity = "Epic",
		Zone = "Ice",
		BaseHP = 180,
		BaseSpeed = 14,
		MoneyPerSecond = 95,
		Color = Color3.fromRGB(113, 246, 236),
	},
	ChillChinchilla = {
		Name = "Chill Chinchilla",
		Rarity = "Legendary",
		Zone = "Ice",
		BaseHP = 250,
		BaseSpeed = 15,
		MoneyPerSecond = 240,
		Color = Color3.fromRGB(190, 182, 255),
	},
	MagmaMoth = {
		Name = "Magma Moth",
		Rarity = "Legendary",
		Zone = "Lava",
		BaseHP = 360,
		BaseSpeed = 16,
		MoneyPerSecond = 620,
		Color = Color3.fromRGB(255, 107, 55),
	},
	EmberEel = {
		Name = "Ember Eel",
		Rarity = "Mythic",
		Zone = "Lava",
		BaseHP = 520,
		BaseSpeed = 17,
		MoneyPerSecond = 1550,
		Color = Color3.fromRGB(255, 68, 105),
	},
	GlitchGloop = {
		Name = "Glitch Gloop",
		Rarity = "Mythic",
		Zone = "Glitch",
		BaseHP = 800,
		BaseSpeed = 18,
		MoneyPerSecond = 4200,
		Color = Color3.fromRGB(68, 255, 159),
	},
	NullNarwhal = {
		Name = "Null Narwhal",
		Rarity = "Divine",
		Zone = "Glitch",
		BaseHP = 1300,
		BaseSpeed = 19,
		MoneyPerSecond = 12000,
		Color = Color3.fromRGB(77, 48, 120),
	},
	PixelPrime = {
		Name = "Pixel Prime",
		Rarity = "Secret",
		Zone = "Glitch",
		BaseHP = 2400,
		BaseSpeed = 21,
		MoneyPerSecond = 60000,
		Color = Color3.fromRGB(255, 255, 255),
	},
}
