return {
	StartingMoney = 0,
	StartingGems = 0,
	BaseDamage = 10,
	AttackRange = 18,
	AttackCooldown = 0.42,
	ChaseDuration = 18,
	StunDuration = 15,
	CaptureRange = 14,
	CaptureRewardSeconds = 10,
	InventoryBaseCapacity = 40,
	StorageUpgradeAmount = 20,
	PlotStandCount = 6,
	MaxBrainrotLevel = 25,
	UpgradeBaseCost = 75,
	UpgradeCostGrowth = 1.68,
	LevelIncomeGrowth = 1.28,
	RebirthBaseCost = 10000,
	RebirthCostGrowth = 3.2,
	RebirthMultiplierPerLevel = 2,
	AutosaveSeconds = 60,
	SpawnTickSeconds = 2.5,
	MaxBrainrotsPerZone = 7,
	CollectTickSeconds = 1,
}
