return {
	{
		Id = "FirstCapture",
		Event = "Capture",
		Target = 1,
		Title = "CATCH YOUR FIRST",
		Description = "Capture 1 pixel creature",
		RewardMoney = 150,
	},
	{
		Id = "FirstPlace",
		Event = "Place",
		Target = 1,
		Title = "START YOUR PLOT",
		Description = "Place 1 creature on a stand",
		RewardMoney = 250,
	},
	{
		Id = "FirstUpgrade",
		Event = "Upgrade",
		Target = 1,
		Title = "POWER IT UP",
		Description = "Upgrade any creature",
		RewardMoney = 400,
	},
	{
		Id = "CaptureFive",
		Event = "Capture",
		Target = 5,
		Title = "BUILD A SQUAD",
		Description = "Own 5 captured creatures",
		RewardMoney = 1000,
	},
	{
		Id = "UnlockDesert",
		Event = "UnlockZone",
		Value = "Desert",
		Target = 1,
		Title = "BREAK INTO DESERT",
		Description = "Unlock the Desert Zone",
		RewardGems = 10,
	},
	{
		Id = "FirstRebirth",
		Event = "Rebirth",
		Target = 1,
		Title = "GO INFINITE",
		Description = "Complete your first rebirth",
		RewardGems = 25,
	},
}
